# Generated by Django 2.2 on 2019-10-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='description',
            field=models.CharField(blank=True, max_length=3000, verbose_name='Полное описание'),
        ),
    ]
