# Generated by Django 2.2 on 2019-11-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20191104_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='created',
            field=models.DateField(blank=True, null=True, verbose_name='дата создание'),
        ),
        migrations.AlterField(
            model_name='team',
            name='ended',
            field=models.DateField(blank=True, null=True, verbose_name='дата окончания'),
        ),
    ]
